dbt_project:
  outputs:
    dev:
      dataset: transformed_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /opt/airflow/service_accounts/your_keyfile_path.json # Update this field with your file name, example: /opt/airflow/service_accounts/airflow-***116-83db69931a10.json
      location: your_dataset_location # Update this field with your dataset location, example: US
      method: service-account
      priority: interactive
      project: your_project_id # Update this field with your BigQuery project ID
      threads: 1
      type: bigquery
  target: dev

  