dbt_project:
  outputs:
    dev:
      dataset: transformed_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/thaliabarrera/Downloads/quickstarts-400312-2c17c9405f0e.json
      location: US
      method: service-account
      priority: interactive
      project: quickstarts-400312
      threads: 1
      type: bigquery
  target: dev