version: 2

sources:
  - name: bigquery
    tables:
      - name: sample_table
        meta:
          dagster:
            asset_key: ["pg_sample_table"] # This metadata specifies the corresponding Dagster asset for this dbt source.

      - name: test_table
        meta:
          dagster:
            asset_key: ["mysql_test_table"] # This metadata specifies the corresponding Dagster asset for this dbt source.